# Generated by Django 5.2.6 on 2025-09-16 19:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '2. مستخدم',
                'verbose_name_plural': '2. المستخدمون',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الموقع')),
                ('client_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('gps_coordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='إحداثيات الموقع')),
                ('gps_radius', models.PositiveIntegerField(default=50, verbose_name='نطاق GPS المسموح به (بالمتر)')),
            ],
            options={
                'verbose_name': '4. موقع',
                'verbose_name_plural': '4. المواقع',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الدور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الدور')),
            ],
            options={
                'verbose_name': '1. دور',
                'verbose_name_plural': '1. الأدوار',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الوردية')),
                ('start_time', models.TimeField(verbose_name='وقت البدء')),
                ('end_time', models.TimeField(verbose_name='وقت الانتهاء')),
            ],
            options={
                'verbose_name': '6. وردية',
                'verbose_name_plural': '6. الورديات',
            },
        ),
        migrations.CreateModel(
            name='UniformItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القطعة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الافتراضي')),
            ],
            options={
                'verbose_name': '16. قطعة زي',
                'verbose_name_plural': '16. قطع الزي',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الرباعي')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الجوال')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب البنكي')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('id_image', models.ImageField(blank=True, null=True, upload_to='id_cards/', verbose_name='صورة الهوية')),
                ('date_of_birth_gregorian', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد (ميلادي)')),
                ('id_expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الهوية')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='api_guard.employee', verbose_name='المشرف المباشر')),
            ],
            options={
                'verbose_name': '3. موظف',
                'verbose_name_plural': '3. الموظفين',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLocationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_guard.location', verbose_name='الموقع')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_guard.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'تعيين موظف لموقع',
                'verbose_name_plural': 'تعيينات الموظفين للمواقع',
                'unique_together': {('employee', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'يومي'), ('monthly', 'شهري'), ('security', 'حالة أمنية'), ('complaint', 'شكوى')], max_length=20, verbose_name='نوع التقرير')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('resolved', 'تم حله'), ('escalated', 'تم تصعيده')], default='new', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_guard.location', verbose_name='الموقع')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api_guard.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': '9. تقرير',
                'verbose_name_plural': '9. التقارير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='report_attachments/', verbose_name='الملف')),
                ('file_type', models.CharField(choices=[('image', 'صورة'), ('video', 'فيديو')], max_length=10, verbose_name='نوع الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الرفع')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api_guard.report', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'مرفق تقرير',
                'verbose_name_plural': 'مرفقات التقارير',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_guard.role', verbose_name='الدور'),
        ),
        migrations.CreateModel(
            name='UniformDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الاستلام')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='القيمة الإجمالية')),
                ('payment_method', models.CharField(choices=[('direct', 'دفع مباشر للمصنع'), ('deduction', 'خصم من الراتب')], max_length=20, verbose_name='طريقة الدفع')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='هل تم إغلاق النموذج؟')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_guard.location', verbose_name='الموقع')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniform_deliveries', to='api_guard.employee', verbose_name='الموظف المستلم')),
                ('operations_assistant_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_uniforms_assistant', to='api_guard.employee', verbose_name='توقيع مساعد المدير')),
                ('operations_manager_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_uniforms_manager', to='api_guard.employee', verbose_name='توقيع رئيس العمليات')),
            ],
            options={
                'verbose_name': '17. نموذج استلام زي',
                'verbose_name_plural': '17. نماذج استلام الزي',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='UniformDeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api_guard.uniformdelivery', verbose_name='نموذج الاستلام')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_guard.uniformitem', verbose_name='القطعة')),
            ],
            options={
                'verbose_name': 'بند في نموذج استلام',
                'verbose_name_plural': 'بنود نماذج الاستلام',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_guard.employee', verbose_name='الموظف')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المكافآت')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصومات')),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة العمل الإضافي')),
                ('pay_date', models.DateField(verbose_name='تاريخ صرف الراتب')),
            ],
            options={
                'verbose_name': '8. راتب',
                'verbose_name_plural': '8. الرواتب',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('flag1', 'إنذار'), ('flag2', 'خصم'), ('flag3', 'فصل')], max_length=10, verbose_name='نوع المخالفة')),
                ('description', models.TextField(verbose_name='وصف المخالفة')),
                ('status', models.CharField(choices=[('pending', 'معلقة'), ('objected', 'تم الاعتراض'), ('action_taken', 'تم اتخاذ إجراء')], default='pending', max_length=20, verbose_name='الحالة')),
                ('action_taken', models.TextField(blank=True, null=True, verbose_name='الإجراء المتخذ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التسجيل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='api_guard.employee', verbose_name='الموظف المخالف')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_violations', to='api_guard.employee', verbose_name='المشرف المُبلغ')),
            ],
            options={
                'verbose_name': '11. مخالفة',
                'verbose_name_plural': '11. المخالفات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المهمة')),
                ('description', models.TextField(verbose_name='وصف المهمة')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة')], default='new', max_length=20, verbose_name='الحالة')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api_guard.location', verbose_name='الموقع')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='api_guard.employee', verbose_name='أُنشئت بواسطة')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='api_guard.employee', verbose_name='مُكلف بها')),
            ],
            options={
                'verbose_name': '5. مهمة',
                'verbose_name_plural': '5. المهام',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('coverage', 'تغطية'), ('transfer', 'نقل'), ('materials', 'طلب مواد')], max_length=20, verbose_name='نوع الطلب')),
                ('description', models.TextField(verbose_name='تفاصيل الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('approval_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات على القرار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='api_guard.employee', verbose_name='الموافق/الرافض')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api_guard.employee', verbose_name='صاحب الطلب')),
            ],
            options={
                'verbose_name': '10. طلب',
                'verbose_name_plural': '10. الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='وصف الطلب اللوجستي')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('in_progress', 'قيد التنفيذ'), ('completed', 'تم التنفيذ')], default='new', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistic_requests', to='api_guard.location', verbose_name='الموقع')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistic_requests', to='api_guard.employee', verbose_name='المشرف الطالب')),
            ],
            options={
                'verbose_name': '15. طلب لوجستي',
                'verbose_name_plural': '15. الطلبات اللوجستية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='assigned_employees',
            field=models.ManyToManyField(related_name='locations', through='api_guard.EmployeeLocationAssignment', to='api_guard.employee'),
        ),
        migrations.CreateModel(
            name='Custody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=255, verbose_name='وصف العهدة')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم التسلسلي (إن وجد)')),
                ('status', models.CharField(choices=[('active', 'في العهدة'), ('returned', 'تم تسليمها')], default='active', max_length=20, verbose_name='الحالة')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodies', to='api_guard.employee', verbose_name='الموظف المسؤول')),
            ],
            options={
                'verbose_name': '14. عهدة',
                'verbose_name_plural': '14. العهد',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_file', models.FileField(upload_to='contracts/', verbose_name='ملف العقد')),
                ('start_date', models.DateField(verbose_name='تاريخ بدء العقد')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء العقد')),
                ('is_signed', models.BooleanField(default=False, verbose_name='هل تم توقيعه؟')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التوقيع')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api_guard.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': '12. عقد',
                'verbose_name_plural': '12. العقود',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(verbose_name='وقت الحضور')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('work_type', models.CharField(choices=[('official', 'دوام رسمي'), ('coverage', 'تغطية'), ('overtime', 'إضافي')], default='official', max_length=20, verbose_name='نوع الدوام')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_guard.location', verbose_name='الموقع')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_guard.shift', verbose_name='الوردية')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api_guard.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': '7. سجل حضور',
                'verbose_name_plural': '7. سجلات الحضور',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليها'), ('rejected', 'مرفوضة'), ('repaying', 'يتم السداد'), ('paid', 'مدفوعة بالكامل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='api_guard.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': '13. سلفة',
                'verbose_name_plural': '13. السلف',
                'ordering': ['-requested_at'],
            },
        ),
    ]
