# Generated by Django 5.2.6 on 2025-09-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-pay_date'], 'verbose_name': '8. راتب', 'verbose_name_plural': '8. الرواتب'},
        ),
        migrations.AlterField(
            model_name='salary',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='pay_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ صرف الراتب'),
        ),
    ]
