# Generated by Codex GPT on 2025-XX-XX

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceViolationPause',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('pause_started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ بدء الإيقاف')),
                ('pause_until', models.DateTimeField(verbose_name='تاريخ انتهاء الإيقاف')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='مدة الإيقاف (دقائق)')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='سبب الإيقاف')),
                ('resumed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إعادة التفعيل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofence_violation_pauses_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_violation_pauses', to='api_guard.employee', verbose_name='الموظف')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geofence_violation_pauses', to='api_guard.location', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': '4.2 إيقاف مخالفة النطاق',
                'verbose_name_plural': '4.2 إيقافات مخالفة النطاق',
                'ordering': ['-pause_started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='geofenceviolationpause',
            index=models.Index(fields=['employee', 'pause_until'], name='geo_pause_emp_until_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceviolationpause',
            index=models.Index(fields=['employee', 'location', 'pause_until'], name='geo_pause_emp_loc_idx'),
        ),
    ]
