# Generated by Django 5.2.6 on 2025-10-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0002_geofenceviolationpause'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='geofenceviolationpause',
            new_name='api_guard_g_employe_97f277_idx',
            old_name='geo_pause_emp_until_idx',
        ),
        migrations.RenameIndex(
            model_name='geofenceviolationpause',
            new_name='api_guard_g_employe_d14bb7_idx',
            old_name='geo_pause_emp_loc_idx',
        ),
    ]
