# Generated by Django 5.2.6 on 2025-09-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0002_passwordresetsms'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelocationassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeelocationassignment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='employeelocationassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('employee', 'location'), name='uniq_active_employee_location'),
        ),
    ]
