# Generated by Django 5.2.6 on 2025-09-22 20:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0003_employeelocationassignment_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShiftAssignment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='وقت بدء مخصص')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='وقت انتهاء مخصص')),
                ('active', models.BooleanField(default=True, verbose_name='نشِطة؟')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='api_guard.employee', verbose_name='الموظف')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_assignments', to='api_guard.location', verbose_name='الموقع')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='api_guard.shift', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'تعيين وردية لموظف',
                'verbose_name_plural': 'تعيينات الورديات للموظفين',
                'unique_together': {('employee', 'shift', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
