# Generated by Django 5.2.6 on 2025-09-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0004_employeeshiftassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='polygon_coords',
            field=models.JSONField(blank=True, help_text='قائمة نقاط [[lat,lng],[lat,lng],...]', null=True, verbose_name='إحداثيات المضلّع'),
        ),
        migrations.AddField(
            model_name='location',
            name='use_polygon',
            field=models.BooleanField(default=False, verbose_name='استخدام مضلّع بدل الدائرة'),
        ),
    ]
