# Generated by Django 5.2.6 on 2025-10-13 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0005_monitoring_reject_and_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='current_stage',
            field=models.CharField(blank=True, choices=[('supervisor', 'المشرف'), ('hr', 'الموارد البشرية'), ('executive', 'الإدارة العليا')], max_length=20, null=True, verbose_name='المرحلة الحالية'),
        ),
        migrations.AddField(
            model_name='report',
            name='last_response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر وقت رد'),
        ),
        migrations.AddField(
            model_name='report',
            name='last_routed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر وقت توجيه'),
        ),
        migrations.AddField(
            model_name='uniformdeliveryitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='المقاس'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'جديدة'), ('accepted', 'مقبولة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'منجزة'), ('deferred', 'مؤجلة'), ('impossible', 'غير ممكن')], default='new', max_length=20, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='ReportMessage',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('sender_role_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='دور المرسل')),
                ('text', models.TextField(verbose_name='النص/التعليمات')),
                ('is_instruction', models.BooleanField(default=True, verbose_name='تعليمات للحارس؟')),
                ('stage', models.CharField(blank=True, choices=[('supervisor', 'المشرف'), ('hr', 'الموارد البشرية'), ('executive', 'الإدارة العليا')], max_length=20, null=True, verbose_name='مرحلة الإرسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='api_guard.report', verbose_name='التقرير')),
                ('sender_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_report_messages', to='api_guard.employee', verbose_name='الموظف المرسل')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_report_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرسل')),
            ],
            options={
                'verbose_name': 'تعليمات/ملاحظة تقرير',
                'verbose_name_plural': 'تعليمات وملاحظات التقارير',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskUpdateLog',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('old_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='الحالة القديمة')),
                ('new_status', models.CharField(max_length=20, verbose_name='الحالة الجديدة')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظة الحارس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التعديل')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_updates', to='api_guard.employee', verbose_name='الموظف')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_updates', to='api_guard.location', verbose_name='الموقع')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='api_guard.task', verbose_name='المهمة')),
            ],
            options={
                'verbose_name': 'سجل تحديث مهمة',
                'verbose_name_plural': 'سجل تحديثات المهام',
                'ordering': ['-created_at'],
            },
        ),
    ]
