# Generated by Django 5.2.6 on 2025-09-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0005_location_polygon_coords_location_use_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshiftassignment',
            name='checkin_grace',
            field=models.PositiveIntegerField(blank=True, help_text='إن تُركت فارغة ⇒ لا سماح للحضور', null=True, verbose_name='سماح الحضور (دقائق)'),
        ),
        migrations.AddField(
            model_name='employeeshiftassignment',
            name='checkout_grace',
            field=models.PositiveIntegerField(blank=True, help_text='تُستخدم فقط إذا كانت ساعات الانصراف فارغة', null=True, verbose_name='سماح الانصراف (دقائق)'),
        ),
        migrations.AddField(
            model_name='employeeshiftassignment',
            name='checkout_grace_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='إن تم تحديدها تتقدّم على الدقائق', max_digits=4, null=True, verbose_name='سماح الانصراف (ساعات)'),
        ),
        migrations.AlterField(
            model_name='employeeshiftassignment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الوردية'),
        ),
    ]
