# Generated by Django 5.2.6 on 2025-09-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0006_employeeshiftassignment_checkin_grace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='early_attachment',
            field=models.FileField(blank=True, null=True, upload_to='early_checkout/'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='early_checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='early_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
