# Generated by Django 5.2.6 on 2025-09-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0007_attendancerecord_early_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('coverage', 'تغطية'), ('leave', 'إجازة'), ('transfer', 'نقل'), ('materials', 'طلب مواد')], max_length=20, verbose_name='نوع الطلب'),
        ),
    ]
