# Generated by Django 5.2.6 on 2025-09-30 21:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0008_alter_request_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='deduction_applied',
            field=models.BooleanField(default=False, help_text='علم إذا تم تحديث خصومات الراتب بهذه السلفة', verbose_name='تم خصم السلفة من الراتب'),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_leave_quota_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='عدد الساعات المتاحة للإجازات في كل شهر', max_digits=6, verbose_name='ساعات الإجازة المسموح بها شهرياً'),
        ),
        migrations.AddField(
            model_name='request',
            name='leave_deducted',
            field=models.BooleanField(default=False, help_text='لمنع الخصم المكرر عند تغيير حالة الطلب', verbose_name='تم خصم الرصيد'),
        ),
        migrations.AddField(
            model_name='request',
            name='leave_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت نهاية الإجازة'),
        ),
        migrations.AddField(
            model_name='request',
            name='leave_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عدد ساعات الإجازة'),
        ),
        migrations.AddField(
            model_name='request',
            name='leave_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت بداية الإجازة'),
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='السنة')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='الشهر')),
                ('quota_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ساعات الإجازة المسموحة')),
                ('used_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ساعات الإجازة المستخدمة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='api_guard.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'رصيد إجازة شهري',
                'verbose_name_plural': 'أرصدة الإجازات الشهرية',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
