# Generated by Django 5.2.6 on 2025-10-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0009_monitoring_absence_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='beneficiary_bank_name',
            field=models.CharField(blank=True, choices=[('alrajhi', 'مصرف الراجحي'), ('snb', 'الأهلي السعودي (SNB)'), ('riyad', 'بنك الرياض'), ('sabb', 'ساب'), ('bsf', 'البنك السعودي الفرنسي'), ('alinma', 'مصرف الإنماء'), ('anb', 'البنك العربي الوطني'), ('jazira', 'بنك الجزيرة'), ('saib', 'البنك السعودي للاستثمار'), ('gib', 'بنك الخليج الدولي')], max_length=20, null=True, verbose_name='بنك المستفيد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='beneficiary_iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='رقم الآيبان للمستفيد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم صاحب الحساب (مستفيد)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='beneficiary_relation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='صلة القرابة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='residency_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الإقامة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='residency_image',
            field=models.ImageField(blank=True, null=True, upload_to='residencies/', verbose_name='صورة الإقامة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='residency_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ إصدار الإقامة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='residency_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الإقامة'),
        ),
    ]
