# Generated by Django 5.2.6 on 2025-10-04 01:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0009_advance_deduction_applied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('device_id', models.CharField(max_length=128, verbose_name='معرّف الجهاز')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم الجهاز')),
                ('platform', models.CharField(blank=True, max_length=50, null=True, verbose_name='النظام')),
                ('app_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='نسخة التطبيق')),
                ('is_trusted', models.BooleanField(default=False, verbose_name='موثوق؟')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='أول ظهور')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخر ظهور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جهاز موثوق',
                'verbose_name_plural': 'الأجهزة الموثوقة',
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='uniq_user_device')],
            },
        ),
    ]
