# Generated by Django 5.2.6 on 2025-10-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0008_trusteddevice_deviceloginchallenge'),
        ('api_guard', '0010_task_status_note_and_uniform_request'),
    ]

    operations = [
    ]
