# Generated by Django 5.2.6 on 2025-10-16 01:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0010_employee_beneficiary_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_file',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='is_signed',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contract',
            name='body',
            field=models.TextField(blank=True, verbose_name='نص العقد'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='نوع العقد'),
        ),
        migrations.AddField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='ملف العقد (PDF)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='sign_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='رمز توقيع عام'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sign_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='صلاحية رابط التوقيع'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='contracts/signatures/', verbose_name='صورة توقيع الموظف'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_company',
            field=models.BooleanField(default=False, verbose_name='توقيع الشركة'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_employee',
            field=models.BooleanField(default=False, verbose_name='توقيع الموظف'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts/signed/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='نسخة PDF موقعة'),
        ),
        migrations.AddField(
            model_name='contract',
            name='title',
            field=models.CharField(default='عقد عمل', max_length=200, verbose_name='عنوان العقد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='education_level',
            field=models.CharField(choices=[('none', 'بدون'), ('high_school', 'ثانوي'), ('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه')], default='none', max_length=20, verbose_name='المؤهل العلمي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='major',
            field=models.CharField(blank=True, max_length=200, verbose_name='التخصص'),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualification_document',
            field=models.FileField(blank=True, null=True, upload_to='qualifications/', verbose_name='ملف المؤهل العلمي (PDF/صور)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البداية'),
        ),
        migrations.CreateModel(
            name='AdditionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم المؤهل/الشهادة')),
                ('file', models.FileField(upload_to='qualifications/extra/', verbose_name='الملف')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_quals', to='api_guard.employee', verbose_name='الموظف')),
            ],
        ),
    ]
