# Generated by Codex CLI on 2025-10-17

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0011_remove_contract_contract_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingIncident',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('incident_type', models.CharField(choices=[('heartbeat_timeout', 'انقطاع نبضات')], max_length=50, verbose_name='نوع الحدث')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الرصد')),
                ('gap_minutes', models.FloatField(blank=True, null=True, verbose_name='مدة الانقطاع (دقائق)')),
                ('timeout_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='مهلة الإعداد (دقائق)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظة')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='بيانات إضافية')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_incidents', to='api_guard.employee', verbose_name='الموظف')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_incidents', to='api_guard.location', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': '7.3 حدث تتبع',
                'verbose_name_plural': '7.3 أحداث التتبع',
                'ordering': ['-recorded_at'],
            },
        ),
    ]

