# Generated by Django 5.2.6 on 2025-10-08 18:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0011_merge_20251008_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMonitoringConfig',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل؟')),
                ('ping_interval_seconds', models.PositiveIntegerField(default=300, help_text='المدة بين كل إرسال إحداثيات من تطبيق الحارس.', verbose_name='الفاصل الزمني للتتبع (ثواني)')),
                ('violation_grace_minutes', models.PositiveIntegerField(default=5, help_text='إذا تجاوز الابتعاد هذه المدة تُنشأ مخالفة تلقائيًا.', verbose_name='مدة السماح قبل تسجيل المخالفة (دقائق)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': '4.1 ضبط مراقبة موقع',
                'verbose_name_plural': '4.1 ضبط مراقبة المواقع',
                'ordering': ['location__name'],
            },
        ),
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('within_radius', models.BooleanField(default=True)),
                ('violation_triggered', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت التسجيل')),
            ],
            options={
                'verbose_name': '7.1 تتبع موقع',
                'verbose_name_plural': '7.1 تتبع المواقع',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='deviceloginchallenge',
            new_name='api_guard_d_user_id_8423b9_idx',
            old_name='api_guard_d_user_id_6ed861_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceloginchallenge',
            new_name='api_guard_d_expires_34237e_idx',
            old_name='api_guard_d_expires_5c3ed4_idx',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='biometric_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='biometric_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='biometric_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_type',
            field=models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('early_check_out', 'Early Check Out')], default='check_in', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_violation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationmonitoringconfig',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_config', to='api_guard.location', verbose_name='الموقع'),
        ),
        migrations.AddField(
            model_name='locationmonitoringconfig',
            name='violation_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_monitoring_configs', to='api_guard.violationrule', verbose_name='المخالفة المعتمدة'),
        ),
        migrations.AddField(
            model_name='locationping',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='api_guard.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='locationping',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_pings', to='api_guard.location', verbose_name='الموقع'),
        ),
    ]
