# Generated by Django 5.2.6 on 2025-10-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0013_locationmonitoringconfig'),
        ('api_guard', '0013_locationping'),
    ]

    operations = [
    ]
