# Generated by Django 5.2.6 on 2025-10-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0012_locationmonitoringconfig_locationping_and_more'),
        ('api_guard', '0014_merge_0013_locationmonitoringconfig_0013_locationping'),
    ]

    operations = [
    ]
