# Generated by Codex on 2025-02-16

from django.db import migrations, models


def drop_old_unique_constraint(apps, schema_editor):
    """
    Safely remove the legacy unique constraint/index on (user, device_id) if it exists.
    Some databases created it with a different automatic name, so we inspect first.
    """
    table_name = "api_guard_trusteddevice"
    wanted_constraint = "uniq_user_device"
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        constraints = connection.introspection.get_constraints(cursor, table_name)

    for name, details in constraints.items():
        if name == wanted_constraint or (
            details.get("unique")
            and set(details.get("columns") or []) == {"user_id", "device_id"}
        ):
            quoted_table = schema_editor.quote_name(table_name)
            quoted_index = schema_editor.quote_name(name)
            schema_editor.execute(f"ALTER TABLE {quoted_table} DROP INDEX {quoted_index}")
            break


def copy_legacy_device_data(apps, schema_editor):
    TrustedDevice = apps.get_model("api_guard", "TrustedDevice")

    for device in TrustedDevice.objects.all().iterator():
        updates = []
        if not getattr(device, "device_hash", ""):
            device.device_hash = getattr(device, "device_id", "") or ""
            updates.append("device_hash")
        legacy_name = getattr(device, "name", None)
        if legacy_name and not getattr(device, "device_name", ""):
            device.device_name = legacy_name
            updates.append("device_name")
        if updates:
            device.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ("api_guard", "0015_merge_20251008_2201"),
    ]

    operations = [
        migrations.RunPython(drop_old_unique_constraint, migrations.RunPython.noop),
        migrations.AddField(
            model_name="trusteddevice",
            name="device_hash",
            field=models.CharField(default="", max_length=128, verbose_name="بصمة الجهاز"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trusteddevice",
            name="device_name",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="اسم الجهاز"),
            preserve_default=False,
        ),
        migrations.RunPython(copy_legacy_device_data, migrations.RunPython.noop),
        migrations.RenameField(
            model_name="trusteddevice",
            old_name="first_seen",
            new_name="first_seen_at",
        ),
        migrations.RenameField(
            model_name="trusteddevice",
            old_name="last_seen",
            new_name="last_seen_at",
        ),
        migrations.RemoveField(
            model_name="trusteddevice",
            name="app_version",
        ),
        migrations.RemoveField(
            model_name="trusteddevice",
            name="device_id",
        ),
        migrations.RemoveField(
            model_name="trusteddevice",
            name="is_trusted",
        ),
        migrations.RemoveField(
            model_name="trusteddevice",
            name="name",
        ),
        migrations.RemoveField(
            model_name="trusteddevice",
            name="platform",
        ),
        migrations.AlterUniqueTogether(
            name="trusteddevice",
            unique_together={("user", "device_hash")},
        ),
    ]
