# Generated by Django 5.2.6 on 2025-10-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0016_contract_created_by_contract_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='guard_capacity',
            field=models.PositiveIntegerField(default=5, verbose_name='سِعة الحراس (للموقع)'),
        ),
        migrations.AddField(
            model_name='shift',
            name='guard_capacity',
            field=models.PositiveIntegerField(default=5, verbose_name='سِعة الحراس (للوردية)'),
        ),
    ]
