# Generated by Django 5.2.6 on 2025-10-19 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0018_data_set_default_capacity_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100, verbose_name='اسم البنك')),
                ('iban', models.CharField(max_length=34, verbose_name='الآيبان')),
                ('account_holder', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم صاحب الحساب')),
                ('swift_bic', models.CharField(blank=True, max_length=20, null=True, verbose_name='SWIFT/BIC')),
                ('branch_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الفرع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='تم الحذف بواسطة')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_rec', to='api_guard.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'الحسابات البنكية',
            },
        ),
        migrations.CreateModel(
            name='BankChangeRequest',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='البنك الحالي')),
                ('current_iban', models.CharField(blank=True, max_length=34, null=True, verbose_name='الآيبان الحالي')),
                ('requested_bank_name', models.CharField(max_length=100, verbose_name='البنك المطلوب')),
                ('requested_iban', models.CharField(max_length=34, verbose_name='الآيبان المطلوب')),
                ('requested_account_holder', models.CharField(blank=True, max_length=200, null=True, verbose_name='صاحب الحساب (مطلوب)')),
                ('requested_swift_bic', models.CharField(blank=True, max_length=20, null=True, verbose_name='SWIFT/BIC')),
                ('requested_branch_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='الفرع')),
                ('note_from_employee', models.TextField(blank=True, null=True, verbose_name='ملاحظة الموظف')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('hr_comment', models.TextField(blank=True, null=True, verbose_name='ملاحظة HR')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القرار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='تم الحذف بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_change_requests', to='api_guard.employee', verbose_name='الموظف')),
                ('hr_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bank_changes', to=settings.AUTH_USER_MODEL, verbose_name='المراجع (HR)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'طلب تعديل حساب بنكي',
                'verbose_name_plural': 'طلبات تعديل الحساب البنكي',
                'indexes': [models.Index(fields=['employee', 'status', 'created_at'], name='api_guard_b_employe_8cf010_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('employee',), name='uniq_pending_bank_change_per_employee')],
            },
        ),
    ]
