@base = http://127.0.0.1:8000
@prefix = api/v1
@json = application/json

### Guard login
POST {{base}}/{{prefix}}/auth/guard/login/
Content-Type: {{json}}

{
  "username": "asma",
  "password": "as@12345678"
}

### Forgot by phone
POST {{base}}/{{prefix}}/auth/password/forgot/phone/
Content-Type: {{json}}

{ "phone": "+966558672670" }

### Reset by phone
POST {{base}}/{{prefix}}/auth/password/reset/phone/
Content-Type: {{json}}

{ "session_id": 1, "code": "123456", "new_password": "NewPass123" }
