# Generated by Django 5.2.6 on 2025-10-17 20:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='policybundle',
            new_name='policies_po_policy__60b580_idx',
            old_name='policies_po_policy__c0f391_idx',
        ),
        migrations.RenameIndex(
            model_name='policytarget',
            new_name='policies_po_scope_642db8_idx',
            old_name='policies_po_scope_r_5b476a_idx',
        ),
        migrations.RenameIndex(
            model_name='policytarget',
            new_name='policies_po_scope_92d6ea_idx',
            old_name='policies_po_scope_l_48abdb_idx',
        ),
        migrations.RenameIndex(
            model_name='policytarget',
            new_name='policies_po_scope_50c910_idx',
            old_name='policies_po_scope_s_1a44b3_idx',
        ),
        migrations.AlterField(
            model_name='policybundle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='policytarget',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
