# Generated by Django 5.2.6 on 2025-10-17 20:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_holidays_weeklyoff_localexception'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='localexception',
            new_name='policies_lo_date_433bd9_idx',
            old_name='policies_lo_date_em_16c24c_idx',
        ),
        migrations.RenameIndex(
            model_name='publicholiday',
            new_name='policies_pu_scope_c23cf8_idx',
            old_name='policies_pu_scope_d_4a60e4_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklyoff',
            new_name='policies_we_scope_d84f2c_idx',
            old_name='policies_we_scope_d_68fd17_idx',
        ),
        migrations.AlterField(
            model_name='localexception',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weeklyoff',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
