# Generated by Django 5.2.6 on 2025-10-17 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_leavepolicy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leavepolicy',
            new_name='policies_le_bundle__00090c_idx',
            old_name='policies_le_bundle_0c0c28_idx',
        ),
        migrations.AlterField(
            model_name='leavepolicy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
