# Generated by Django 5.2.6 on 2025-10-17 20:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_overtime_rewards_policy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='overtimerewardspolicy',
            new_name='policies_ov_bundle__53c79e_idx',
            old_name='policies_ov_bundle_bfa191_idx',
        ),
        migrations.AlterField(
            model_name='overtimerewardspolicy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
