"""
Django settings for sanam_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import importlib

from pathlib import Path
from dotenv import load_dotenv
load_dotenv()


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "t", "yes", "on"}


def _env_int(name: str, default: int) -> int:
    raw = os.getenv(name)
    try:
        return int(raw) if raw is not None else default
    except (TypeError, ValueError):
        return default


BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")  # مهم: يشير لملف .env بجوار manage.py


EMAIL_BACKEND = os.getenv(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
EMAIL_USE_SSL = _env_bool("SMTP_USE_SSL", False)
EMAIL_USE_TLS = _env_bool("SMTP_USE_TLS", not EMAIL_USE_SSL)
if EMAIL_USE_SSL:
    EMAIL_USE_TLS = False  # لا يمكن تفعيل كليهما معًا
EMAIL_PORT = _env_int("SMTP_PORT", 465 if EMAIL_USE_SSL else 587)
EMAIL_HOST_USER = os.getenv("SMTP_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("SMTP_PASS", "")
EMAIL_TIMEOUT = _env_int("SMTP_TIMEOUT", 20)

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@sanam.local")
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)
EMAIL_SUBJECT_PREFIX = os.getenv("EMAIL_SUBJECT_PREFIX", "[Sanam] ")
EMAIL_REPLY_TO = os.getenv("DEFAULT_REPLY_TO")

GEOFENCE_ALERT_RECIPIENTS = [
    addr.strip()
    for addr in os.getenv("GEOFENCE_ALERT_RECIPIENTS", "san2025am@gmail.com").split(",")
    if addr.strip()
]

GEOFENCE_OUTSIDE_WARNING_MINUTES = _env_int("GEOFENCE_OUTSIDE_WARNING_MINUTES", 60)
GEOFENCE_OUTSIDE_DEDUCTION_PERCENT = _env_int("GEOFENCE_OUTSIDE_DEDUCTION_PERCENT", 2)

# Attendance/Geofence hardening toggles
ENABLE_DEVICE_BINDING = _env_bool("ENABLE_DEVICE_BINDING", False)
MIN_GPS_ACCURACY_M = _env_int("MIN_GPS_ACCURACY_M", 50)

# Play Integrity (server-side enforcement is optional; app may still send tokens)
ENFORCE_PLAY_INTEGRITY = _env_bool("ENFORCE_PLAY_INTEGRITY", False)
_allowed_raw = os.getenv("INTEGRITY_ALLOWED_VERDICTS", "MEETS_DEVICE_INTEGRITY,MEETS_STRONG_INTEGRITY")
INTEGRITY_ALLOWED_VERDICTS = [s.strip() for s in _allowed_raw.split(",") if s.strip()]

# Optional IP/ASN provider hooks (not enforced by default)
MAXMIND_DB_PATH = os.getenv("MAXMIND_DB_PATH")
IPINFO_TOKEN = os.getenv("IPINFO_TOKEN")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'CHANGE_ME_IN_ENV')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1','true','yes')
# أثناء التطوير يمكنك رؤية الكود في الاستجابة:
DEBUG_SMS_ECHO = True   # ← سنستعمله لإظهار الكود للاختبار فقط


_raw_hosts = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts if h.strip()]
if '31.97.158.157' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('31.97.158.157')
# Application definition

_HAS_JAZZMIN = importlib.util.find_spec('jazzmin') is not None

INSTALLED_APPS = [
    *(['jazzmin'] if _HAS_JAZZMIN else []),
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    *(['import_export'] if importlib.util.find_spec('import_export') is not None else []),
    'rest_framework',
    'rest_framework_simplejwt',
    # تطبيقاتك الخاصة (Local apps)
    'api_guard',
    'admin_extras',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
]
AUTH_USER_MODEL = 'api_guard.User'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sanam_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sanam_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# sanam_project/settings.py

# قاعدة البيانات قابلة للتهيئة عبر البيئة، مع سقوط تلقائي إلى SQLite في التطوير
DB_ENGINE = os.getenv('DB_ENGINE', '').lower()
MYSQL_HOST = os.getenv('MYSQL_HOST')
DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('MYSQL_DB', 'sanam_db'),
            'USER': os.getenv('MYSQL_USER', 'sanam_user'),
            'PASSWORD': os.getenv('MYSQL_PASSWORD', 'Asmg36@2022'),
            'HOST': MYSQL_HOST or '31.97.158.157',
            'PORT': os.getenv('MYSQL_PORT', '3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Riyadh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# في نهاية ملف settings.py
STATIC_ROOT = BASE_DIR / 'staticfiles' # مجلد سيتم تجميع كل الملفات الثابتة فيه


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ... (في نهاية الملف)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# إعدادات Simple JWT (اختياري لكن موصى به)
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # مدة صلاحية الـ Access Token (مثلاً: ساعة)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),      # مدة صلاحية الـ Refresh Token (مثلاً: يوم)
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True, # تحديث حقل last_login في موديل المستخدم

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY, # يستخدم المفتاح السري للمشروع للتوقيع
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',), # نوع التوثيق: "Bearer <token>"
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}


SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0"))
SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "False").lower() == "true"
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "False").lower() == "true"
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", "False").lower() == "true"
X_FRAME_OPTIONS = "DENY"

# Optional CORS/CSRF via env
CORS_ALLOWED_ORIGINS = [o for o in os.getenv('DJANGO_CORS_ALLOWED_ORIGINS','').split(',') if o]
CSRF_TRUSTED_ORIGINS = [o for o in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS','').split(',') if o]

# Jazzmin settings
JAZZMIN_SETTINGS = {
    'site_title': 'لوحة إدارة سنم',
    'site_header': 'إدارة سنم',
    'site_brand': 'Sanam Admin',
    'welcome_sign': 'مرحباً بك في لوحة إدارة سنم',
    'site_logo': 'admin_extras/img/logo.png',
    'login_logo': 'admin_extras/img/logo.png',
    'site_logo_classes': 'img-circle',
    'copyright': 'Sanam',
    'show_ui_builder': True,
    'topmenu_links': [
        {'name': 'Dashboard', 'url': 'admin_extras:dashboard', 'permissions': ['auth.view_user']},
        {'name': 'Chat', 'url': 'admin_extras:chat', 'permissions': ['auth.view_user']},
        {'model': 'api_guard.user'},
        {'app': 'api_guard'},
    ],
    'icons': {
        'auth.user': 'fas fa-user',
        'auth.Group': 'fas fa-users',
        'api_guard.employee': 'fas fa-id-badge',
        'api_guard.location': 'fas fa-map-marker-alt',
        'api_guard.report': 'fas fa-file-alt',
        'api_guard.request': 'fas fa-envelope-open-text',
        'admin_extras.chatmessage': 'fas fa-comments',
    },
    'custom_css': 'admin_extras/css/brand.css',
} if _HAS_JAZZMIN else {}

JAZZMIN_UI_TWEAKS = {
    'theme': 'darkly',
    'dark_mode_theme': 'darkly',
    'sidebar_fixed': True,
    'navbar_fixed': True,
} if _HAS_JAZZMIN else {}
