# Generated by Django 5.2.6 on 2025-10-18 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_extras', '0002_chatmessage_created_by_chatmessage_deleted_by_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='الرمز')),
                ('title', models.CharField(max_length=120, verbose_name='الاسم')),
                ('admin_path', models.CharField(help_text='مثال: /admin/hr/', max_length=200, verbose_name='رابط اللوحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل؟')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='الترتيب')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='تم الحذف بواسطة')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='المجموعة المرتبطة')),
                ('permissions', models.ManyToManyField(blank=True, related_name='functional_sections', to='auth.permission', verbose_name='الصلاحيات')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'قسم وظيفي',
                'verbose_name_plural': 'الأقسام الوظيفية',
                'ordering': ['order', 'code'],
            },
        ),
    ]
