# Generated by Django 5.2.6 on 2025-10-15 22:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الرباعي')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='الإيميل')),
                ('education_level', models.CharField(choices=[('none', 'بدون'), ('high_school', 'ثانوي'), ('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه')], default='none', max_length=20, verbose_name='المؤهل العلمي')),
                ('major', models.CharField(blank=True, max_length=200, verbose_name='التخصص')),
                ('qualification_document', models.FileField(blank=True, null=True, upload_to='qualifications/', verbose_name='ملف المؤهل العلمي (PDF/صور)')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عقد عمل', max_length=200, verbose_name='عنوان العقد')),
                ('contract_type', models.CharField(blank=True, max_length=100, verbose_name='نوع العقد')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='ملف العقد (PDF)')),
                ('body', models.TextField(blank=True, verbose_name='نص العقد')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='contracts/signatures/', verbose_name='صورة توقيع الموظف')),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to='contracts/signed/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='نسخة PDF موقعة')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التوقيع')),
                ('signed_by_employee', models.BooleanField(default=False, verbose_name='توقيع الموظف')),
                ('signed_by_company', models.BooleanField(default=False, verbose_name='توقيع الشركة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.employee', verbose_name='الموظف')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم المؤهل/الشهادة')),
                ('file', models.FileField(upload_to='qualifications/extra/', verbose_name='الملف')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_quals', to='hr.employee', verbose_name='الموظف')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الرباعي')),
                ('national_id', models.CharField(max_length=20, verbose_name='رقم الهوية')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='الإيميل')),
                ('position', models.CharField(choices=[('guard', 'حارس أمن'), ('supervisor', 'مشرف'), ('hr', 'موارد بشرية')], max_length=20, verbose_name='الوظيفة المتقدم لها')),
                ('resume', models.FileField(blank=True, null=True, upload_to='applications/resumes/', verbose_name='السيرة الذاتية')),
                ('qualification_document', models.FileField(blank=True, null=True, upload_to='applications/qualifications/', verbose_name='المؤهل العلمي')),
                ('cover_letter', models.TextField(blank=True, verbose_name='رسالة توضيحية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('under_review', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='new', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الموارد البشرية')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee', verbose_name='الموظف المرتبط')),
            ],
        ),
    ]
