# Generated by Django 5.2.6 on 2025-10-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='sign_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='رمز توقيع عام'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sign_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='صلاحية رابط التوقيع'),
        ),
    ]
