# Generated by Django 5.2.6 on 2025-10-16 01:07

import django.db.models.deletion
from django.db import migrations, models


def _clear_jobapplication_employee_fk(apps, schema_editor):
    """قبل تحويل مرجع employee إلى api_guard.employee،
    أزل القيم القديمة التي تشير إلى hr.Employee حتى لا تنكسر القيود في SQLite.
    لاحقًا يمكن ربطها يدويًا أو عبر ترحيل بيانات حسب national_id.
    """
    JobApplication = apps.get_model('hr', 'JobApplication')
    db = schema_editor.connection.alias
    JobApplication.objects.using(db).update(employee=None)


class Migration(migrations.Migration):

    dependencies = [
        ('api_guard', '0011_remove_contract_contract_file_and_more'),
        ('hr', '0002_contract_sign_token_contract_sign_token_expires_at'),
    ]

    operations = [
        # أزل مراجع hr.Employee من طلبات التوظيف قبل تغيير الـ FK
        migrations.RunPython(_clear_jobapplication_employee_fk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='contract',
            name='employee',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_guard.employee', verbose_name='الموظف المرتبط'),
        ),
        migrations.DeleteModel(
            name='AdditionalQualification',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
