# Generated by Django 5.2.6 on 2025-10-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_jobapplication_created_by_jobapplication_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name': 'طلب وظيفة', 'verbose_name_plural': 'طلبات وظائف'},
        ),
    ]
