# Generated by Django 5.2.6 on 2025-10-17 20:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_guard', '0014_leave_days_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConfig',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('daily_rate_policy', models.CharField(choices=[('fixed', 'ثابت'), ('from_base', 'من الراتب الأساسي')], default='from_base', max_length=20, verbose_name='سياسة اليومية')),
                ('fixed_daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='اليومية الثابتة')),
                ('default_working_days', models.DecimalField(decimal_places=2, default=30, max_digits=6, verbose_name='الأيام القياسية')),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=5, verbose_name='ساعات العمل في اليوم')),
                ('max_deduction_rate', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='الحد الأقصى للخصم (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل؟')),
            ],
            options={
                'verbose_name': 'إعداد الرواتب',
                'verbose_name_plural': 'إعدادات الرواتب',
            },
        ),
        migrations.CreateModel(
            name='PayrollCycle',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('month', models.PositiveIntegerField(verbose_name='الشهر')),
                ('status', models.CharField(choices=[('draft', 'مسودّة'), ('closed', 'مقفلة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='payroll.payrollconfig', verbose_name='الإعداد المستخدم')),
            ],
            options={
                'verbose_name': 'دورة راتب',
                'verbose_name_plural': 'دورات الرواتب',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('default_working_days', models.DecimalField(decimal_places=2, default=30, max_digits=6)),
                ('unpaid_leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payable_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('days_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions_requested', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('carry_in_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions_applied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions_excess_carried', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('detail', models.JSONField(blank=True, null=True, verbose_name='تفاصيل')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payrollcycle', verbose_name='الدورة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_items', to='api_guard.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'بند راتب',
                'verbose_name_plural': 'بنود الرواتب',
                'indexes': [models.Index(fields=['employee', 'cycle'], name='payroll_pay_employe_7b22e1_idx')],
            },
        ),
    ]
