# Generated by Django 5.2.6 on 2025-10-17 20:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_reward_overtime'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='overtime',
            new_name='payroll_ove_employe_94cb28_idx',
            old_name='payroll_ove_employee_e8f8d7_idx',
        ),
        migrations.RenameIndex(
            model_name='reward',
            new_name='payroll_rew_employe_50fa86_idx',
            old_name='payroll_rew_employee_37cfe6_idx',
        ),
        migrations.AlterField(
            model_name='overtime',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='allowances_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي البدلات'),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي'),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='carry_in_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='خصومات مرحلة من الشهر السابق'),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='اليومية'),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='days_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الأيام'),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='deductions_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الخصومات المطبقة'),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='deductions_excess_carried',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='خصومات فائضة مرحّلة'),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='deductions_requested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الخصومات المطلوبة'),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='default_working_days',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=6, verbose_name='الأيام القياسية'),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي قبل الخصم'),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الصافي المستحق'),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='overtime_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الإضافي'),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='payable_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='أيام مستحقة الدفع'),
        ),
        migrations.AlterField(
            model_name='payrollitem',
            name='unpaid_leave_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='أيام الإجازة غير المدفوعة'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
